channels:
- pytorch
- huggingface
- nvidia
- conda-forge
- http://conda.anaconda.org/gurobi
- defaults
channel_priority: disabled
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- abseil-cpp=20211102.0=hd4dd3e8_0
- aiohttp=3.9.3=py311h5eee18b_0
- aiosignal=1.2.0=pyhd3eb1b0_0
- arrow-cpp=14.0.2=h374c478_1
- attrs=23.1.0=py311h06a4308_0
- aws-c-auth=0.6.19=h5eee18b_0
- aws-c-cal=0.5.20=hdbd6064_0
- aws-c-common=0.8.5=h5eee18b_0
- aws-c-compression=0.2.16=h5eee18b_0
- aws-c-event-stream=0.2.15=h6a678d5_0
- aws-c-http=0.6.25=h5eee18b_0
- aws-c-io=0.13.10=h5eee18b_0
- aws-c-mqtt=0.7.13=h5eee18b_0
- aws-c-s3=0.1.51=hdbd6064_0
- aws-c-sdkutils=0.1.6=h5eee18b_0
- aws-checksums=0.1.13=h5eee18b_0
- aws-crt-cpp=0.18.16=h6a678d5_0
- aws-sdk-cpp=1.10.55=h721c034_0
- blas=1.0=mkl
- blinker=1.6.2=py311h06a4308_0
- boost-cpp=1.82.0=hdb19cb5_2
- boto3=1.34.82=py311h06a4308_0
- botocore=1.34.82=py311h06a4308_0
- bottleneck=1.3.7=py311hf4808d0_0
- bravado=11.0.3=pyhd8ed1ab_0
- bravado-core=5.17.1=pyhd8ed1ab_0
- brotli-python=1.0.9=py311h6a678d5_8
- bzip2=1.0.8=h5eee18b_6
- c-ares=1.19.1=h5eee18b_0
- ca-certificates=2024.2.2=hbcca054_0
- certifi=2024.2.2=pyhd8ed1ab_0
- cffi=1.16.0=py311h5eee18b_1
- charset-normalizer=2.0.4=pyhd3eb1b0_0
- click=8.1.7=py311h06a4308_0
- cryptography=42.0.5=py311hdda0065_0
- cuda-cudart=11.8.89=0
- cuda-cupti=11.8.87=0
- cuda-libraries=11.8.0=0
- cuda-nvrtc=11.8.89=0
- cuda-nvtx=11.8.86=0
- cuda-runtime=11.8.0=0
- dataclasses=0.8=pyh6d0b6a4_7
- datasets=2.19.0=py_0
- dill=0.3.6=py311h06a4308_0
- ffmpeg=4.3=hf484d3e_0
- filelock=3.13.1=py311h06a4308_0
- freetype=2.12.1=h4a9f257_0
- frozenlist=1.4.0=py311h5eee18b_0
- fsspec=2024.3.1=py311h06a4308_0
- future=0.18.3=py311h06a4308_0
- gflags=2.2.2=h6a678d5_1
- gitdb=4.0.7=pyhd3eb1b0_0
- gitpython=3.1.37=py311h06a4308_0
- glog=0.5.0=h6a678d5_1
- gmp=6.2.1=h295c915_3
- gmpy2=2.1.2=py311hc9b5ff0_0
- gnutls=3.6.15=he1e5248_0
- grpc-cpp=1.48.2=he1ff14a_1
- huggingface_hub=0.23.0rc1=py_0
- icu=73.1=h6a678d5_0
- idna=3.7=py311h06a4308_0
- intel-openmp=2023.1.0=hdb19cb5_46306
- jinja2=3.1.3=py311h06a4308_0
- jmespath=1.0.1=py311h06a4308_0
- jpeg=9e=h5eee18b_1
- jsonref=1.1.0=pyhd8ed1ab_0
- jsonschema=4.19.2=py311h06a4308_0
- jsonschema-specifications=2023.7.1=py311h06a4308_0
- krb5=1.20.1=h143b758_1
- lame=3.100=h7b6447c_0
- lcms2=2.12=h3be6417_0
- ld_impl_linux-64=2.38=h1181459_1
- lerc=3.0=h295c915_0
- libblas=3.9.0=1_h86c2bf4_netlib
- libboost=1.82.0=h109eef0_2
- libbrotlicommon=1.0.9=h5eee18b_8
- libbrotlidec=1.0.9=h5eee18b_8
- libbrotlienc=1.0.9=h5eee18b_8
- libcblas=3.9.0=5_h92ddd45_netlib
- libcublas=11.11.3.6=0
- libcufft=10.9.0.58=0
- libcufile=1.9.1.3=0
- libcurand=10.3.5.147=0
- libcurl=8.5.0=h251f7ec_0
- libcusolver=11.4.1.48=0
- libcusparse=11.7.5.86=0
- libdeflate=1.17=h5eee18b_1
- libedit=3.1.20230828=h5eee18b_0
- libev=4.33=h7f8727e_1
- libevent=2.1.12=hdbd6064_1
- libffi=3.4.4=h6a678d5_1
- libgcc-ng=13.2.0=h77fa898_6
- libgfortran-ng=13.2.0=h69a702a_6
- libgfortran5=13.2.0=h43f5ff8_6
- libgomp=13.2.0=h77fa898_6
- libiconv=1.16=h5eee18b_3
- libidn2=2.3.4=h5eee18b_0
- libjpeg-turbo=2.0.0=h9bf148f_0
- liblapack=3.9.0=5_h92ddd45_netlib
- libnghttp2=1.57.0=h2d74bed_0
- libnpp=11.8.0.86=0
- libnvjpeg=11.9.0.86=0
- libpng=1.6.39=h5eee18b_0
- libprotobuf=3.20.3=he621ea3_0
- libssh2=1.10.0=hdbd6064_3
- libstdcxx-ng=13.2.0=hc0a3c3a_6
- libtasn1=4.19.0=h5eee18b_0
- libthrift=0.15.0=h1795dd8_2
- libtiff=4.5.1=h6a678d5_0
- libunistring=0.9.10=h27cfd23_0
- libuuid=1.41.5=h5eee18b_0
- libwebp-base=1.3.2=h5eee18b_0
- llvm-openmp=14.0.6=h9e868ea_0
- lz4-c=1.9.4=h6a678d5_1
- markupsafe=2.1.3=py311h5eee18b_0
- mkl=2023.1.0=h213fc3f_46344
- mkl-service=2.4.0=py311h5eee18b_1
- mkl_fft=1.3.8=py311h5eee18b_0
- mkl_random=1.2.4=py311hdb19cb5_0
- monotonic=1.5=py_0
- mpc=1.1.0=h10f8cd9_1
- mpfr=4.0.2=hb69a4c5_1
- mpmath=1.3.0=py311h06a4308_0
- msgpack-python=1.0.3=py311hdb19cb5_0
- multidict=6.0.4=py311h5eee18b_0
- multiprocess=0.70.14=py311h06a4308_0
- ncurses=6.4=h6a678d5_0
- neptune-client=0.16.15=pyhd8ed1ab_0
- nettle=3.7.3=hbbd107a_1
- networkx=3.1=py311h06a4308_0
- numexpr=2.8.7=py311h65dcdc2_0
- numpy=1.26.4=py311h08b1b3b_0
- numpy-base=1.26.4=py311hf175353_0
- oauthlib=3.2.2=py311h06a4308_0
- openh264=2.1.1=h4ff587b_0
- openjpeg=2.4.0=h3ad879b_0
- openssl=3.3.0=hd590300_0
- orc=1.7.4=hb3bc3d3_1
- packaging=23.2=py311h06a4308_0
- pandas=2.2.1=py311ha02d727_0
- pillow=10.3.0=py311h5eee18b_0
- pip=23.3.1=py311h06a4308_0
- psutil=5.9.0=py311h5eee18b_0
- pyarrow=14.0.2=py311hb6e97c4_0
- pyarrow-hotfix=0.6=pyhd8ed1ab_0
- pycparser=2.21=pyhd3eb1b0_0
- pyjwt=2.4.0=py311h06a4308_0
- pysocks=1.7.1=py311h06a4308_0
- python=3.11.5=h955ad1f_0
- python-dateutil=2.8.2=pyhd3eb1b0_0
- python-tzdata=2023.3=pyhd3eb1b0_0
- python-xxhash=2.0.2=py311h5eee18b_1
- python_abi=3.11=2_cp311
- pytorch=2.3.0=py3.11_cuda11.8_cudnn8.7.0_0
- pytorch-cuda=11.8=h7e8668a_5
- pytorch-mutex=1.0=cuda
- pytz=2024.1=py311h06a4308_0
- pyyaml=6.0.1=py311h5eee18b_0
- re2=2022.04.01=h295c915_0
- readline=8.2=h5eee18b_0
- referencing=0.30.2=py311h06a4308_0
- regex=2023.10.3=py311h5eee18b_0
- requests=2.31.0=py311h06a4308_1
- requests-oauthlib=1.3.0=py_0
- responses=0.13.3=pyhd3eb1b0_0
- rpds-py=0.10.6=py311hb02cf49_0
- s2n=1.3.27=hdbd6064_0
- s3transfer=0.10.1=py311h06a4308_0
- safetensors=0.4.2=py311h24d97f6_0
- scipy=1.13.0=py311h64a7726_0
- setuptools=68.2.2=py311h06a4308_0
- simplejson=3.17.6=py311h5eee18b_0
- six=1.16.0=pyhd3eb1b0_1
- smmap=4.0.0=pyhd3eb1b0_0
- snappy=1.1.10=h6a678d5_1
- sqlite=3.45.3=h5eee18b_0
- swagger-spec-validator=3.0.3=pyhd8ed1ab_0
- sympy=1.12=py311h06a4308_0
- tbb=2021.8.0=hdb19cb5_0
- tk=8.6.12=h1ccaba5_0
- tokenizers=0.19.1=py311h6640629_0
- torchaudio=2.3.0=py311_cu118
- torchtriton=2.3.0=py311
- torchvision=0.18.0=py311_cu118
- tqdm=4.66.2=py311h92b7b1e_0
- transformers=4.40.1=pyhd8ed1ab_0
- typing=3.10.0.0=py311h06a4308_0
- typing-extensions=4.9.0=py311h06a4308_1
- typing_extensions=4.9.0=py311h06a4308_1
- tzdata=2024a=h04d1e81_0
- urllib3=2.1.0=py311h06a4308_1
- utf8proc=2.6.1=h5eee18b_1
- websocket-client=0.58.0=py311h06a4308_4
- wheel=0.41.2=py311h06a4308_0
- xxhash=0.8.0=h7f8727e_3
- xz=5.4.6=h5eee18b_1
- yaml=0.2.5=h7b6447c_0
- yarl=1.9.3=py311h5eee18b_0
- zlib=1.2.13=h5eee18b_1
- zstd=1.5.5=hc292b87_1
- pip:
  - absl-py==2.1.0
  - accelerate==0.34.2
  - annotated-types==0.7.0
  - anyio==4.6.0
  - cloudpickle==3.0.0
  - datasets==2.19.0
  - diskcache==5.6.3
  - distro==1.9.0
  - einops==0.8.0
  - fastapi==0.115.0
  - gguf==0.10.0
  - h11==0.14.0
  - httpcore==1.0.6
  - httptools==0.6.1
  - httpx==0.27.2
  - huggingface-hub==0.25.1
  - importlib_metadata==8.5.0
  - interegular==0.3.3
  - jiter==0.5.0
  - joblib==1.4.0
  - jsonschema==4.23.0
  - lark==1.2.2
  - llvmlite==0.43.0
  - lm-format-enforcer==0.10.6
  - mistral_common==1.4.4
  - mkl-service==2.4.0
  - monotonic==1.5
  - msgspec==0.18.6
  - nest-asyncio==1.6.0
  - nltk==3.8.1
  - numba==0.60.0
  - nvidia-cublas-cu12==12.1.3.1
  - nvidia-cuda-cupti-cu12==12.1.105
  - nvidia-cuda-nvrtc-cu12==12.1.105
  - nvidia-cuda-runtime-cu12==12.1.105
  - nvidia-cudnn-cu12==9.1.0.70
  - nvidia-cufft-cu12==11.0.2.54
  - nvidia-curand-cu12==10.3.2.106
  - nvidia-cusolver-cu12==11.4.5.107
  - nvidia-cusparse-cu12==12.1.0.106
  - nvidia-ml-py==12.560.30
  - nvidia-nccl-cu12==2.20.5
  - nvidia-nvjitlink-cu12==12.6.77
  - nvidia-nvtx-cu12==12.1.105
  - openai==1.51.0
  - outlines==0.0.46
  - partial-json-parser==0.2.1.1.post4
  - peft==0.13.0
  - prometheus-fastapi-instrumentator==7.0.0
  - prometheus_client==0.21.0
  - protobuf==5.28.2
  - py-cpuinfo==9.0.0
  - pyairports==2.1.1
  - pycountry==24.6.1
  - pydantic==2.9.2
  - pydantic_core==2.23.4
  - python-dotenv==1.0.1
  - pyzmq==26.2.0
  - ray==2.37.0
  - requests-oauthlib==1.3.0
  - rouge-score==0.1.2
  - safetensors==0.4.5
  - scikit-learn==1.5.2
  - sentencepiece==0.2.0
  - sniffio==1.3.1
  - starlette==0.38.6
  - threadpoolctl==3.5.0
  - tiktoken==0.7.0
  - tokenizers==0.20.0
  - torch==2.4.0
  - torchaudio==2.3.0
  - torchvision==0.19.0
  - transformers==4.45.1
  - triton==3.0.0
  - typing_extensions==4.12.2
  - uvicorn==0.31.0
  - uvloop==0.20.0
  - vllm==0.6.2
  - watchfiles==0.24.0
  - websockets==13.1
  - xformers==0.0.27.post2
  - zipp==3.20.2
